name: AthariumEntreprise
version: '${project.version}'
main: fr.itmozlegends.AthariumEntreprise
api-version: '1.20'
depend: [Vault]
commands:
  entreprise:
    description: Gère les entreprises
    usage: /entreprise
